### PR TITLE
Sf doc convention

### PR DESCRIPTION
**Pull request by iowillhoit**
### What does this PR do?
Formats description to match SF conventions
Feedback from this PR https://github.com/salesforcecli/cli/pull/103

### What issues does this PR fix or reference?
[@W-10260114@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10260114)

### CODE REVIEW

**Comment by iowillhoit** [comment]
Here is a screenshot of the output
Screen Shot 2021-12-06 at 2 11 18 PM

**Comment by iowillhoit** [comment]
Here is the updated help doc output:
Screen Shot 2021-12-06 at 3 32 28 PM

**Comment by iowillhoit** [comment]
@mshanemc Also added the header we discussed to this PR. This will help differentiate `sfdx` and `sf` release notes when they both display when running `sfdx update` (both hooks will fire since `sf` ships with `sfdx`). 
Screen Shot 2021-12-06 at 3 34 57 PM

**Review by mshanemc — APPROVED** [review]
I'm fine with it using `sf` convention instead of `sfdx`

**Review by jshackell-sfdc — APPROVED** [review]

**Pull request merged**
